drop table MEETINGROOM;

create table MEETINGROOM(
	MNUM			NUMBER,
	RNAME		  	VARCHAR2(20),
	USER_TEL		VARCHAR2(30),
	MSUBJECT		VARCHAR2(50),
	MTIME			VARCHAR2(5),
	USER_NAME		VARCHAR2(30)
);

